// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2caalfdlYNr7HReC4nzoRbJUcrsyovCQ',
    appId: '1:263122717606:web:f4569afca8c40b3bf7dd67',
    messagingSenderId: '263122717606',
    projectId: 'gossip-95893',
    authDomain: 'gossip-95893.firebaseapp.com',
    databaseURL: 'https://gossip-95893-default-rtdb.firebaseio.com',
    storageBucket: 'gossip-95893.appspot.com',
    measurementId: 'G-ZVEYBWCTT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRuzPFQl4wjXo1yn9kp5o2HSZCV6TmHDY',
    appId: '1:263122717606:android:d715061e3904880ef7dd67',
    messagingSenderId: '263122717606',
    projectId: 'gossip-95893',
    databaseURL: 'https://gossip-95893-default-rtdb.firebaseio.com',
    storageBucket: 'gossip-95893.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdZ6-KioL6TadBihF1sAnRuGxckReWmc',
    appId: '1:263122717606:ios:e8f6c5021dd8ba41f7dd67',
    messagingSenderId: '263122717606',
    projectId: 'gossip-95893',
    databaseURL: 'https://gossip-95893-default-rtdb.firebaseio.com',
    storageBucket: 'gossip-95893.appspot.com',
    iosClientId: '263122717606-nb3lbm6mlv0i87lqn792k1i6a2quatda.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdZ6-KioL6TadBihF1sAnRuGxckReWmc',
    appId: '1:263122717606:ios:e8f6c5021dd8ba41f7dd67',
    messagingSenderId: '263122717606',
    projectId: 'gossip-95893',
    databaseURL: 'https://gossip-95893-default-rtdb.firebaseio.com',
    storageBucket: 'gossip-95893.appspot.com',
    iosClientId: '263122717606-nb3lbm6mlv0i87lqn792k1i6a2quatda.apps.googleusercontent.com',
    iosBundleId: 'com.example.gossipApp',
  );
}
